//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shoe()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ShoeID { get; set; }
        public int ShoeCategoryID { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int BrandID { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public string ShoeImage { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> Size { get; set; }
        public string Color { get; set; }
        public Nullable<int> ShoeTypeID { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ShoeCategory ShoeCategory { get; set; }
        public virtual ShoeStatus ShoeStatus { get; set; }
        public virtual ShoeType ShoeType { get; set; }
    }
}
